### ISSUE TITLE
Increase support for uppercase letters

### ISSUE THREAD

**Issue by heennkkee** [mosbth/ctextfilter#6]
Continuing in this repo for [issue#10](https://github.com/mosbth/Anax-oophp/issues/10)...

If the only aspect if the performance, the amount of calls to `strtolower()` would then be the same, but the amount of code would be less if the class took care of it itself. 

Relating to the [issue#4](https://github.com/mosbth/ctextfilter/issues/4) it would require the user to iterate through his loop first, to make everything lowercase, then pass it to the class and then the class does an additional iteration to perform the filters, resulting in two iterations.

**Comment by mosbth** [comment]
Updated to always do convert incoming filter-string to lowercase.
