### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by marcusgsta** [mosbth/ctextfilter#7]
One of the requirements is michelf/php-markdown 1.6.
Now the latest version of michelf/php-markdown is 1.7,
so due to requirements in composer.json, ctextfilter will not install.

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mos/ctextfilter v1.2.9 requires michelf/php-markdown 1.6.* -> satisfiable by michelf/php-markdown[1.6.0] but these conflict with your requirements or minimum-stability.`

**Comment by mosbth** [comment]
michelf/php-markdown 1.7 was installed in composer.json, removed it and it worked as expected.
